### ISSUE TITLE
[BUG] PaywallOverrides doesn't work in Superwall.track

### ISSUE THREAD

**Issue by quanganhdo** [superwall-me/SuperwallKit-iOS#102]
## New issue checklist
- [x] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [x] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `Superwall` version: 3.0.0-beta.1
- iOS version(s):
- CocoaPods/Carthage version (if applicable):
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Describe the bug

https://github.com/superwall-me/SuperwallKit-iOS/blob/master/Sources/SuperwallKit/Dependencies/DependencyContainer.swift#L217-L244

`paywallOverrides` isn't used in the function body.

### Steps to reproduce
Please also include a description of expected vs. actual behaviour

### Other Information
e.g. stacktraces, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.

**Comment by yusuftor** [comment]
Great catch, thank you!!
