### ISSUE TITLE
[FEATURE REQUEST] Superwall.shared.handleDeepLink should return BOOL

### ISSUE THREAD

**Issue by quanganhdo** [superwall-me/SuperwallKit-iOS#106]
**Is your feature request related to a problem? Please describe.**

`handleDeepLink` should return BOOL so it can be better integrated with existing code (`true` if the URL is handled / it's a valid preview URL, `false` otherwise).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yusuftor** [comment]
Thanks, I'll add this

**Comment by yusuftor** [comment]
FYI this is out in `3.0.0-beta.4` now
